/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

import net.ltgt.gradle.errorprone.errorprone
import org.gradle.api.tasks.compile.JavaCompile
import org.gradle.api.tasks.testing.Test
import org.gradle.api.plugins.quality.Pmd

plugins {
    java
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    pmd
    id("com.github.spotbugs") version "6.0.27"
    id("net.ltgt.errorprone") version "4.1.0"
    id("me.champeau.jmh") version "0.7.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val isReleaseBuild = providers.gradleProperty("release")
    .map { it.equals("true", ignoreCase = true) }
    .getOrElse(false)

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // ErrorProne
    errorprone("com.google.errorprone:error_prone_core:2.36.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.mips.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// ErrorProne — enable on all compile tasks
tasks.withType<JavaCompile>().configureEach {
    options.errorprone.isEnabled = isReleaseBuild && !name.contains("Jmh", ignoreCase = true)
}

// PMD — error-prone patterns and real bugs only (bestpractices excluded: too noisy on test code)
pmd {
    isConsoleOutput = true
    ruleSets = listOf(
        "category/java/errorprone.xml"
    )
}
tasks.withType<Pmd>().configureEach {
    enabled = isReleaseBuild
}

// SpotBugs — static bug detection
spotbugs {
    ignoreFailures = false
}
tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    enabled = isReleaseBuild
    reports.create("html") { required = true }
    reports.create("xml") { required = true }
}

// JMH benchmarks
jmh {
    warmupIterations = 3
    warmup = "1s"
    iterations = 5
    fork = 1
    timeOnIteration = "1s"
    benchmarkMode = listOf("avgt")
    timeUnit = "ns"
}

// Fat/executable JAR — bundles all runtime deps so the jar is self-contained
tasks.named<Jar>("jar") {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
    archiveFileName.set("mips-sim.jar")
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Git pre-commit hook — runs `check` (tests + all static analysis) before every commit
tasks.register("installGitHooks") {
    notCompatibleWithConfigurationCache("One-time setup task that writes to .git/hooks")
    doLast {
        val hookFile = rootProject.file(".git/hooks/pre-commit")
        hookFile.writeText("#!/bin/sh\n./gradlew check\n")
        hookFile.setExecutable(true)
        println("Installed pre-commit hook.")
    }
}
